apiVersion: v2
name: cloud-bot
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0


dependencies:
- name: common
  version: 0.1.0
  repository: "http://zetta.ai/helm-charts/charts"