service:
  type: NodePort
nameOverride: amqp
fullnameOverride: amqp
image:
  registry: docker.io
  repository: bitnami/rabbitmq
  tag: 3.8.9-debian-10-r0
  pullPolicy: IfNotPresent
auth:
  username: test
  password: test
plugins: ""
extraPlugins: ""
replicaCount: 1
nodeSelector:
  cloud.google.com/gke-nodepool: rabbitmq
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 20
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1
persistence:
  enabled: false